#! /bin/sh -e

. /lib/lsb/init-functions
test -f /etc/default/artvaluereport2-staging && . /etc/default/artvaluereport2-staging

case "$1" in
  start)
    test -x /usr/bin/artvaluereport2-staging || exit 0
    log_begin_msg "Starting artvaluereport2-staging..."
    mkdir -p /srv/artvaluereport2-staging
    export ArtValueReport_datadir=/usr/share/ArtValueReport
    "start-stop-daemon" "--start" "-b" "--make-pidfile" "-d" "/srv/artvaluereport2-staging" "--exec" "/usr/bin/artvaluereport2-staging" "--pidfile" "/var/run/artvaluereport2-staging" "--" "--http-port" "9031" "--base-uri" "http://seereason.com:9031/" "--top" "/srv/artvaluereport2-staging" "--logs" "/var/log/artvaluereport2-staging" "--log-mode" "Development" "--static" "/usr/share/artvaluereport2-data" "--no-validate"
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping artvaluereport2-staging..."
    "start-stop-daemon" "--stop" "--oknodo" "--retry=60" "--pidfile" "/var/run/artvaluereport2-staging"
    log_end_msg $?
    ;;
  *)
    log_success_msg "Usage: ${0} {start|stop}"
    exit 1
esac

exit 0
