#! /bin/sh -e

. /lib/lsb/init-functions
test -f /etc/default/artvaluereport2-development && . /etc/default/artvaluereport2-development

case "$1" in
  start)
    test -x /usr/bin/artvaluereport2-development || exit 0
    log_begin_msg "Starting artvaluereport2-development..."
    mkdir -p /srv/artvaluereport2-development
    export ArtValueReport_datadir=/usr/share/ArtValueReport
    "start-stop-daemon" "--start" "-b" "--make-pidfile" "-d" "/srv/artvaluereport2-development" "--exec" "/usr/bin/artvaluereport2-development" "--pidfile" "/var/run/artvaluereport2-development" "--" "--http-port" "9032" "--base-uri" "http://seereason.com:9032/" "--top" "/srv/artvaluereport2-development" "--logs" "/var/log/artvaluereport2-development" "--log-mode" "Development" "--static" "/usr/share/artvaluereport2-data" "--no-validate"
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping artvaluereport2-development..."
    "start-stop-daemon" "--stop" "--oknodo" "--retry=60" "--pidfile" "/var/run/artvaluereport2-development"
    log_end_msg $?
    ;;
  *)
    log_success_msg "Usage: ${0} {start|stop}"
    exit 1
esac

exit 0
